// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaR7PLS25_paP44HxSjSNEsL1WKoqx4l4',
    appId: '1:516847826416:web:885b6eea6c38ed0f29d935',
    messagingSenderId: '516847826416',
    projectId: 'zenithapp-9570a',
    authDomain: 'zenithapp-9570a.firebaseapp.com',
    storageBucket: 'zenithapp-9570a.firebasestorage.app',
    measurementId: 'G-Y7MWJ9KQJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqrkqDEc07tiRm46Y-KuKFOCeW0EJGpOc',
    appId: '1:516847826416:android:3f493d02ee25cc6329d935',
    messagingSenderId: '516847826416',
    projectId: 'zenithapp-9570a',
    storageBucket: 'zenithapp-9570a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD94T0kvmTN1B-PVqH9zuRgsVI-gSHXM4c',
    appId: '1:516847826416:ios:42bfa53916bf528e29d935',
    messagingSenderId: '516847826416',
    projectId: 'zenithapp-9570a',
    storageBucket: 'zenithapp-9570a.firebasestorage.app',
    iosBundleId: 'com.example.zenithapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD94T0kvmTN1B-PVqH9zuRgsVI-gSHXM4c',
    appId: '1:516847826416:ios:42bfa53916bf528e29d935',
    messagingSenderId: '516847826416',
    projectId: 'zenithapp-9570a',
    storageBucket: 'zenithapp-9570a.firebasestorage.app',
    iosBundleId: 'com.example.zenithapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaR7PLS25_paP44HxSjSNEsL1WKoqx4l4',
    appId: '1:516847826416:web:c621c41d019f363029d935',
    messagingSenderId: '516847826416',
    projectId: 'zenithapp-9570a',
    authDomain: 'zenithapp-9570a.firebaseapp.com',
    storageBucket: 'zenithapp-9570a.firebasestorage.app',
    measurementId: 'G-2DR0CK85X7',
  );
}
